version: '2'
services:
  wiremock:
    image: rodolpheche/wiremock:2.26.3-alpine
    container_name: wiremock
    volumes:
      - ./src/test/resources/wiremock/:/home/wiremock/
    ports:
      - "8080:8080"
      - "8443:8443"
    command:
      --global-response-templating
    networks:
      - wiremock-network

networks:
  wiremock-network:
    driver: bridge
